"""empty message

Revision ID: 16be2294d9a0
Revises: e4c1e47299c4
Create Date: 2020-01-14 14:06:45.674110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16be2294d9a0'
down_revision = 'e4c1e47299c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('valid_reset_password_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'valid_reset_password_token')
    # ### end Alembic commands ###
